### ISSUE TITLE
Don't see any notification after posting comment

### ISSUE THREAD

**Issue by bazalt** [sbrajesh/bp-activity-comment-notifier#3]
Hi,

I may have missed something: I can't mange to make this plugin work. 
1. Logged as userA, I post a comment on UserB's post.
2. Logged as UserB, I don't see any notification, even in admin, in "Activity" menu.

Disabled all other plugins but BuddyPress (v2.4.3) and BuddyPress Activity Comment Notifier (v1.1.2). 
Switched theme for the default Twenty*
No error in log.

**Comment by sbrajesh** [comment]
Hi,
This plugin creates notification when you comment on another user's update. By post, I am assuming you mean activity update?

Is your notification component enabled? Also, The notifications are available from Your Profile->Notification page in the frontend.
Can you please check that and let me know?

Thank you
Brajesh

**Comment by bazalt** [comment]
My bad... I though the plugin create notifications on post comments, not activity comments. I should have read more slowly. Sorry for the inconvenience. I will search further (unless you already know such plugin?)

**Comment by sbrajesh** [comment]
Hi,
No problem.
Is this something that you may be looking for?
http://buddydev.com/plugins/bp-notify-post-author-blog-comment/

**Comment by bazalt** [comment]
Exactly. In fact, I stumbled on your bp-activity-comment-notifier repo after visiting this page. I wrongly though that this repo was a rewrite of the bp-notify-post-author-blog-comment plugin. 
Is there a way to contribute to this plugin (I need it to be translatable too :laughing: )

**Comment by sbrajesh** [comment]
Sorry about that. Still, Thank you for contributing the translations on this.
The other plugin is available here
https://github.com/buddydev/bp-notify-post-author-on-blog-comment

Thank you
Brajesh
